[general]
fps_counter = true
judge_offset = 0

[paths]
tja_path = 'Songs'
video_path = 'Videos'

[keybinds]
left_kat = ['E','R']
left_don = ['F','K']
right_don = ['J','D']
right_kat = ['I','U']

[audio]
device_type = 'ASIO'
asio_buffer = 6

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
vsync = true
