[general]
fps_counter = false
judge_offset = 0
autoplay = true
sfx = true
language = 'ja'

[paths]
tja_path = ['E:/Taiko/ESE', 'Songs', 'E:/Taiko/VersionSort']
video_path = 'Videos'

[keybinds]
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[audio]
device_type = 'ASIO'
buffer_size = 6
sample_rate = 48000
exclusive = false

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
vsync = false
