[general]
fps_counter = false
judge_offset = 0
visual_offset = 0
autoplay = false
sfx = true
language = "ja"

[paths]
tja_path = ['Songs']
video_path = 'Videos'

[keybinds]
left_kat = ['D']
left_don = ['F']
right_don = ['J']
right_kat = ['K']

[audio]
device_type = "Windows WASAPI"
buffer_size = 22
sample_rate = 44100
exclusive = false

[video]
screen_width = 1280
screen_height = 720
fullscreen = false
borderless = false
vsync = true
