name: Build Audio Library (Windows MSYS2)

on:
  workflow_dispatch:
  push:
    paths:
      - "libs/audio/**"
      - ".github/workflows/build_audio.yml"

jobs:
  build-msys2:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-portaudio
            mingw-w64-x86_64-libsndfile
            mingw-w64-x86_64-libsamplerate

      - name: Build audio library (DLL)
        shell: msys2 {0}
        working-directory: libs/audio
        run: |
          make clean
          make all

      - name: List build outputs
        shell: msys2 {0}
        working-directory: libs/audio
        run: |
          ls -l

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: libaudio-dll
          path: libs/audio/libaudio.dll
