name: Build Audio Library (Windows)

on:
  workflow_dispatch:
  push:
    paths:
      - "libs/audio/**"
      - ".github/workflows/windows-audio-build.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_INSTALLATION_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg.exe install portaudio:x64-windows libsndfile:x64-windows libsamplerate:x64-windows

      - name: Add vcpkg include/lib paths to environment
        run: |
          echo "VCPKG_INCLUDE_PATH=${{ github.workspace }}\vcpkg\installed\x64-windows\include" >> $env:GITHUB_ENV
          echo "VCPKG_LIB_PATH=${{ github.workspace }}\vcpkg\installed\x64-windows\lib" >> $env:GITHUB_ENV

      - name: Build audio library
        working-directory: libs/audio
        run: |
          nmake /f Makefile all

      - name: List build outputs
        working-directory: libs/audio
        run: |
          dir

      - name: Clean build artifacts
        working-directory: libs/audio
        run: |
          nmake /f Makefile clean
