name: Build PortAudio lib
on:
  push:
    branches-ignore:
      - master
permissions:
  # This is needed for pushing a new commit to the repo:
  contents: write
jobs:
  macos:
    runs-on: macos-latest
    env:
      CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    steps:
      - name: checkout portaudio
        uses: actions/checkout@v5
        with:
          repository: PortAudio/portaudio
          ref: v19.7.0
          path: portaudio
      - name: cmake configure
        run: |
          cmake -S portaudio -B build -D CMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5
      - name: cmake build
        run: |
          cmake --build build
      - name: move static library
        run: |
          mv build/libportaudio.a .
      - name: show some information about static library
        run: |
          file libportaudio.a
          lipo -info libportaudio.a
      - name: upload static library
        uses: actions/upload-artifact@v4
        with:
          name: macos-static-lib
          path: libportaudio.a
  push:
    runs-on: ubuntu-latest
    needs: [macos]
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v5
      - name: Retrieve static library
        uses: actions/download-artifact@v5
        with:
          name: macos-static-lib
      - name: Commit and push binaries (if there are changes)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update binaries" && git push || true
