name: PyTaiko
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions:
    contents: read
jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Check-out repository
              uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                  enable-cache: true
            - name: Setup Python
              run: uv python install 3.11
            - name: Install Dependencies
              run: |
                  uv sync
            - name: Build Executable
              uses: Nuitka/Nuitka-Action@main
              with:
                  nuitka-version: 2.6.7
                  script-name: PyTaiko.py
                  mode: app
                  output-dir: .
                  include-module: raylib,moviepy,numpy,sounddevice,tomlkit
                  #include-package: imageio_ffmpeg
                  noinclude-setuptools-mode: nofollow
                  noinclude-IPython-mode: nofollow
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: PyTaiko ${{ runner.os }} Build
                  path: |
                      Graphics/*
                      Sounds/*
                      Videos/*
                      config.toml
                      *.exe
                      *.bin
                      *.app/**/*
